# Generated by Django 4.2.5 on 2023-09-30 01:52

from django.db import migrations, models
import inventario.validators


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "permissions": [
                    ("reporte_cantidad", "Visualizar la cantidad reporte"),
                    ("reporte_detalle", "Reporte detallado de cantidades"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[inventario.validators.validation_categoria],
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[inventario.validators.validar_par],
            ),
        ),
    ]
